version: '3.7'
services:
  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${PO_PASSWORD}
      - POSTGRES_USER=root
      - POSTGRES_DBNAME=test
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/pgadmin

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
    ports:
      - 5480:80